// <auto-generated />
using System;
using BuffMeUp.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuffMeUp.Backend.Migrations
{
    [DbContext(typeof(BuffMeUpDbContext))]
    partial class BuffMeUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.JT_User_Role", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("JT_User_Role");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonalStatsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalStatsId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1"),
                            Email = "admin@admin.admin",
                            FirstName = "Admin",
                            PasswordHash = "0+aHb2blzweBVbO5jMNrZg==.CKghctKS/o/0h/PXFwj9jG2Vil6tBbp2iXZgSF+wmZs=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTemplateId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.ExerciseTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e12ec542-6fad-41df-989d-8cecd399c40e"),
                            Description = "Lie on your back on a flat bench. Grip the bar with your hands slightly wider than shoulder-width apart. Lift the bar off the rack and position it above your chest with arms fully extended.",
                            ExerciseType = 1,
                            IsGlobal = true,
                            Name = "Bench Press",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("204cced3-4d3c-489e-94fe-f6c44f5736ae"),
                            Description = "Stand with your mid-foot under the barbell. Bend over and grab the bar with a shoulder-width grip. Bend your knees until your shins touch the bar. Lift your chest up and straighten your lower back.",
                            ExerciseType = 0,
                            IsGlobal = true,
                            Name = "Deadlift",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("73fda4d9-7112-408f-8340-6caef6c5bc6a"),
                            Description = "Stand with your mid-foot under the barbell. Bend over and grab the bar with a shoulder-width grip. Bend your knees until your shins touch the bar. Lift your chest up and straighten your lower back.",
                            ExerciseType = 2,
                            IsGlobal = true,
                            Name = "Squat",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("60ffc373-b8e0-4273-94fd-b10e03691619"),
                            Description = "Stand with the bar on your front shoulders, and your hands next to your shoulders. Press the bar over your head, until it’s balanced over your shoulders and mid-foot.",
                            ExerciseType = 3,
                            IsGlobal = true,
                            Name = "Overhead Press",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("3dc21d83-5e9a-47d2-8759-cf9ee45901dd"),
                            Description = "Grab the pull-up bar with your palms down (shoulder-width grip). Hang to the pull-up bar with straight arms and your legs off the floor. Pull yourself up by pulling your elbows down to the floor.",
                            ExerciseType = 0,
                            IsGlobal = true,
                            Name = "Pull-up",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("01764429-c0c4-4a59-bd11-bfeea1921350"),
                            Description = "Stand up with your torso upright while holding a dumbbell on each hand being held at arms length. The elbows should be close to the torso. This will be your starting position.",
                            ExerciseType = 5,
                            IsGlobal = true,
                            Name = "Dumbbell Curl",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("6771b6a7-9c77-493f-ae94-40a426a0d84f"),
                            Description = "Attach a straight or angled bar to a high pulley and grab with an overhand grip at shoulder width. Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor.",
                            ExerciseType = 4,
                            IsGlobal = true,
                            Name = "Triceps Pushdown",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        },
                        new
                        {
                            Id = new Guid("21b21dc7-770a-4932-bc2e-a7af085e2ccd"),
                            Description = "Lie on your back on the floor. Bend your legs and place feet firmly on the ground to stabilize your lower body. Cross your hands to opposite shoulders or place them behind your ears, without pulling on your neck.",
                            ExerciseType = 6,
                            IsGlobal = true,
                            Name = "Sit-up",
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        });
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fats")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.JT_MealTemplate_FoodItem", b =>
                {
                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.HasKey("MealId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("JT_MealTemplate_FoodItem");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MealTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.MealTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealTemplates");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.PersonalStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<int>("GoalWeight")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("StartingWeight")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalStats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36d33f78-dcba-46a7-955c-13e0cc73ec97"),
                            Age = 22,
                            CurrentWeight = 0,
                            Gender = true,
                            GoalWeight = 75,
                            Height = 175,
                            StartingWeight = 70,
                            UserId = new Guid("41fc7ca7-c54c-4e7b-a68a-033f054b56d1")
                        });
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.JT_User_Role", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.Role", "Role")
                        .WithMany("User_Role")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.User", "User")
                        .WithMany("User_Role")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.User", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.PersonalStats", "PersonalStats")
                        .WithMany()
                        .HasForeignKey("PersonalStatsId");

                    b.Navigation("PersonalStats");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.ExerciseSet", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Exercises.ExerciseTemplate", "ExerciseTemplate")
                        .WithMany()
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuffMeUp.Backend.Data.Models.Exercises.Workout", "Workout")
                        .WithMany("ExerciseSets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseTemplate");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.ExerciseTemplate", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.User", "User")
                        .WithMany("ExerciseTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.Workout", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.JT_MealTemplate_FoodItem", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Food.FoodItem", "FoodItem")
                        .WithMany("MealTemplate_FoodItemm")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuffMeUp.Backend.Data.Models.Food.MealTemplate", "Meal")
                        .WithMany("MealTemplate_FoodItem")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.Meal", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Food.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId");

                    b.HasOne("BuffMeUp.Backend.Data.Models.Food.MealTemplate", "MealTemplate")
                        .WithMany()
                        .HasForeignKey("MealTemplateId");

                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("MealTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.MealTemplate", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.User", "User")
                        .WithMany("MealTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.PersonalStats", b =>
                {
                    b.HasOne("BuffMeUp.Backend.Data.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.Role", b =>
                {
                    b.Navigation("User_Role");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Auth.User", b =>
                {
                    b.Navigation("ExerciseTemplates");

                    b.Navigation("MealTemplates");

                    b.Navigation("Meals");

                    b.Navigation("User_Role");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Exercises.Workout", b =>
                {
                    b.Navigation("ExerciseSets");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.FoodItem", b =>
                {
                    b.Navigation("MealTemplate_FoodItemm");
                });

            modelBuilder.Entity("BuffMeUp.Backend.Data.Models.Food.MealTemplate", b =>
                {
                    b.Navigation("MealTemplate_FoodItem");
                });
#pragma warning restore 612, 618
        }
    }
}
